# Configuration settings for the comparative study. See config.py for more information regarding the specific configuration options. 
EVAL:
  MODEL_NAME: "hrnet_ocr"
  DISPLAY_IMAGE: True 
  BATCH_SIZE: 1
  INPUT_SIZE: # re-size input img to model to new size.
    RESIZE_IMG: True # will only re-size the image to the dim below if True
    HEIGHT: 640
    WIDTH: 1024

TRAIN:
  MODEL_NAME: 'deeplabv3plus'
  CRITERION: 'crossentropyloss'
  BATCH_SIZE: 2
  TOTAL_EPOCHS: 10
  LR: 1.0e-5 # learning rate 
  FINAL_LR: 1.0e-7
  INPUT_SIZE:
    RESIZE_IMG: True
    HEIGHT: 320
    WIDTH: 512
    
MODELS: 
  UNET: # --> unet
    MODEL_FILE: "model.pt"
    BASE: 40 # base channel amount for the U-Net, increases in further layers
    KERNEL_SIZE: 5
  # --> deeplabv3plus
  DEEPLABV3PLUS: 
    ENCODER: 'resnet101'
    ENCODER_WEIGHTS: 'imagenet'
  # --> hrnet_ocr
  HRNET_OCR:  
    CONFIG: "models/HRNet-Semantic-Segmentation-HRNet-OCR/experiments/rellis/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml"
    MODEL_FILE: "/home/jplangger/Documents/Dev/VBTC/src/temp/hrnet_best/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484/best.pth"
    # "/home/jplangger/Documents/Dev/VBTC/src/models/HRNet-Semantic-Segmentation-HRNet-OCR/output/rellis/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484/final_state.pth"
    SRC_DIR: "/home/jplangger/Documents/Dev/VBTC/src/models/HRNet-Semantic-Segmentation-HRNet-OCR"  
  # --> gscnn
  GSCNN: 
    MODEL_FILE: "/home/jplangger/Documents/Dev/VBTC/src/models/GSCNN-master/output/gscnn_best.pth"
    SRC_DIR: "/home/jplangger/Documents/Dev/VBTC/src/models/GSCNN-master"


