# Configuration settings for the comparative study. See config.py for more information regarding the specific configuration options. 
EVAL:
  MODEL_NAME: "unet"
  # hrnet_ocr
  # unet
  DISPLAY_IMAGE: True 
  BATCH_SIZE: 1
  INPUT_SIZE: # re-size input img to model to new size.
    RESIZE_IMG: False # will only re-size the image to the dim below if True
    HEIGHT: 640
    WIDTH: 1024
  
MODELS: 
  UNET: 
    MODEL_FILE: #"model.pt"
  HRNET_OCR:  
    CONFIG: "models/HRNet-Semantic-Segmentation-HRNet-OCR/experiments/rellis/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml"
    MODEL_FILE: "/home/jplangger/Documents/Dev/VBTC/src/temp/hrnet_best/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484/best.pth"
    # "/home/jplangger/Documents/Dev/VBTC/src/models/HRNet-Semantic-Segmentation-HRNet-OCR/output/rellis/seg_hrnet_ocr_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484/final_state.pth"
    SRC_DIR: "/home/jplangger/Documents/Dev/VBTC/src/models/HRNet-Semantic-Segmentation-HRNet-OCR"
  GSCNN: 
    MODEL_FILE: "/home/jplangger/Documents/Dev/VBTC/src/models/GSCNN-master/output/gscnn_best.pth"
    SRC_DIR: "/home/jplangger/Documents/Dev/VBTC/src/models/GSCNN-master"


